server:
  port: 8762

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVIC
                fallbackuri: forward:/UserFallBack
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVIC
                fallbackuri: forward:/UserFallBack


eureka:
  client:
    register-with-eureka: true
    fetch-registor: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost